blank_issues_enabled: false

contact_links:
  - name: 📖 Contribution Guide
    url: https://github.com/ternaryss/rest2go/blob/develop/CONTRIBUTING.md
    about: Read the contribution guidelines before reporting bug or requesting new feature.
